version: '3.3'
services:
  cassandra:
    image: cassandra:4.0
    ports:
      - 9042:9042
    volumes:
      - ~/apps/cassandra:/var/lib/cassandra
    environment:
      - CASSANDRA_CLUSTER_NAME=fakenews
    restart: always

  stream:
    platform: linux/amd64
    # build:  ./services/stream/Dockerfile.test
    image:  testx4
    container_name: stream
    environment:
      - DB_CONNECTION=cassandra
      - BATCH_SIZE=1000
    ports:
    # for spark UI
      - 4040:4040
    volumes:
      - ./data:/data
      - ./services/stream:/stream
    command:
      spark-submit stream.py
    depends_on:
      - "cassandra"
  visualization:
    # image:  vizualization
    build: ./services/visualization/FinalVisualization
    container_name:  vizualization
    environment:
      - DB_CONNECTION=cassandra
    ports:
      - 5001:5001
    depends_on:
      - "cassandra"
    restart: unless-stopped
